[package]
name = "umber-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
same-file = "1"
clap = { version = "3.2.8", features = ["derive"] }
colored = "2.0.0"